import FooterComponent from "@/components/footer";
import HeaderComponents from "@/components/header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
const myFont = localFont({
  src: "../public/HousttelySignature-GOonZ.ttf",
  variable: "--font-house",
});

export const metadata: Metadata = {
  title: "Bruno Truong",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body data-barba="wrapper" className="">
        <div className="content_container">
          <HeaderComponents />
          {children}
          <FooterComponent />
        </div>
      </body>
    </html>
  );
}
